"""Cloudflare DNS and tunnel management via the official Python SDK"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_core.ipynb.

# %% auto #0
__all__ = ['CF', 'repo_root', 'mv_skill_md']

# %% ../nbs/00_core.ipynb #a6e48b4c
from cloudflare import Cloudflare
from fastcore.all import L, first, Path

# %% ../nbs/00_core.ipynb #297e5764
class CF:
    'Cloudflare API wrapper using the official cloudflare Python SDK'
    def __init__(self, token=None, timeout=10, **kw):
        self._c = Cloudflare(api_token=token, timeout=timeout, **kw)

    def zones(self) -> list:
        'List all zones'
        return [z.model_dump() for z in self._c.zones.list()]

    def zone_id(self, domain) -> str:
        'Get zone_id for domain'
        for z in self._c.zones.list(name=domain): return z.id
        raise ValueError(f'Zone not found: {domain}')

    def dns_records(self, zone_id) -> list:
        'List DNS records for a zone'
        return [r.model_dump() for r in self._c.dns.records.list(zone_id=zone_id)]

    def create_record(self, zone_id, type, name, content, ttl=1, proxied=False) -> dict:
        'Create a DNS record'
        r = self._c.dns.records.create(zone_id=zone_id, type=type, name=name, content=content, ttl=ttl, proxied=proxied)
        return r.model_dump()

    def delete_record(self, zone_id, record_id) -> None:
        'Delete a DNS record'
        self._c.dns.records.delete(record_id, zone_id=zone_id)

    def upsert_record(self, domain, name, content, type='A', proxied=False) -> dict:
        'Skip if record already matches; otherwise delete any same-name conflicts and create.'
        zid = self.zone_id(domain)
        f = name if '.' in name else f'{name}.{domain}'
        existing = list(self._c.dns.records.list(zone_id=zid, name=f))
        for r in existing:
            if r.type == type and r.content == content: return r.model_dump()
            self.delete_record(zid, r.id)
        return self.create_record(zid, type, name, content, proxied=proxied)

    def account_id(self) -> str:
        'Get first account ID'
        for a in self._c.accounts.list(): return a.id
        raise ValueError('No accounts found')

    def tunnels(self, account_id=None) -> list:
        'List Cloudflare tunnels'
        aid = account_id or self.account_id()
        return [t.model_dump() for t in self._c.zero_trust.tunnels.cloudflared.list(account_id=aid)]

    def tunnel_id(self, name, account_id=None) -> str:
        'Get tunnel ID by name'
        t = first(L(self.tunnels(account_id=account_id)).filter(lambda x: x.get('name') == name))
        if t is None: raise ValueError(f'Tunnel not found: {name}')
        return t['id']

    def create_tunnel(self, name, account_id=None) -> dict:
        'Create a new Cloudflare tunnel'
        aid = account_id or self.account_id()
        t = self._c.zero_trust.tunnels.cloudflared.create(account_id=aid, name=name)
        return t.model_dump()

    def delete_tunnel(self, tunnel_id, account_id=None) -> None:
        'Delete a Cloudflare tunnel'
        aid = account_id or self.account_id()
        self._c.zero_trust.tunnels.cloudflared.delete(tunnel_id, account_id=aid)

    def tunnel_token(self, tunnel_id, account_id=None) -> str:
        'Get tunnel token string for use with cloudflared_svc() / CF_TUNNEL_TOKEN env var'
        aid = account_id or self.account_id()
        result = self._c.zero_trust.tunnels.cloudflared.token.get(tunnel_id, account_id=aid)
        return result if isinstance(result, str) else result.token

    def tunnel_cname(self, domain: str, name: str, tunnel_id: str, proxied: bool = True) -> dict:
	    'Point subdomain at a tunnel (CNAME to *.cfargotunnel.com).'
	    return self.upsert_record(domain, name, f"{tunnel_id}.cfargotunnel.com",
	                              type='CNAME', proxied=proxied)

    def verify(self) -> dict:
        '''Check token validity and which permission groups are available (read-only, non-destructive).

        Required token permissions per capability:
        - dns_read:     Zone:DNS:Read  (or Zone:DNS:Edit)
        - account_read: Account:Account Settings:Read
        - tunnel_read:  Account:Cloudflare Tunnel:Edit  +  account_read
        '''
        try:
	        acc = self.account_id()
	        return dict(result=bool(self._c.zones.list() and self._c.zero_trust.tunnels.cloudflared.list(account_id=acc)))
        except Exception as e: return dict(result=False, err=str(e))

    def setup_tunnel(self, domain: str, name: str | None = None, tunnel_name: str | None = None, proxied: bool = True):
        ''' One-liner for VPS hosting. Creates (or reuses) a tunnel, sets up the CNAME subdomain,
        and returns (tunnel_id, token) ready for cloudflared_svc() in your docker-compose.

        Usage:
            tid, token = setup_tunnel("example.com", "app")   # → app.example.com
            tid, token = setup_tunnel("example.com")          # → example.com (apex, CNAME-flattened)
            # then in Compose:
            # .svc("cloudflared", **cloudflared_svc(token_env=...)) with CF_TUNNEL_TOKEN=token
        '''
        n = name or domain
        tname = tunnel_name or n
        exists = L.filter(lambda x: x.get('name') == tname)
        tid = first(t)['id'] if (t:=exists(self.tunnels())) else self.create_tunnel(tname)['id']
        self.tunnel_cname(domain, n, tid, proxied=proxied)
        return tid, self.tunnel_token(tid)

# %% ../nbs/00_core.ipynb #357004bb
def repo_root() -> Path:
    'Find the root of the current git repository, or None if not in a repo.'
    return first((Path.cwd(), *Path.cwd().parents), lambda p: (p/'.git').exists())

def mv_skill_md(dry_run=True, dir=None) -> None:
    'Copy bundled SKILL.md to .agents/skills/cfeasy/ and .claude/skills/cfeasy/ at project root.'
    base = Path(__file__).parent if '__file__' in globals() else Path.cwd()
    if not (src := base/'SKILL.md').exists(): return
    root = dir or repo_root() or '.'
    ts = [Path(root)/'.agents/skills/cfeasy/SKILL.md', Path(root)/'.claude/skills/cfeasy/SKILL.md']
    if dry_run: print(f'Would copy {src} to: {list(map(str,ts))}')
    else:
        for t in ts: t.mk_write(src.read_text(encoding='utf-8'))
        print(f'Installed -> {list(map(str,ts))}')
